"""
01_clean_survey.py -- prepare the raw survey export for analysis.

Reads   : ../data/raw/GENAI_survey-export_20260812_v01.csv   (never modified)
Writes  : ../data/processed/GENAI_survey-clean_20260814_v02.csv
          ../data/processed/GENAI_cleaning-log_20260814_v02.md

Every change made to the data is appended to the cleaning log with the row and
column affected and the reason, so that any number in the report can be traced
back to the raw export. Run this before 02_analyse_survey.py.

Usage: python 01_clean_survey.py
"""

from pathlib import Path
import pandas as pd

HERE = Path(__file__).resolve().parent
RAW = HERE.parent / "data" / "raw" / "GENAI_survey-export_20260812_v01.csv"
OUT = HERE.parent / "data" / "processed" / "GENAI_survey-clean_20260814_v02.csv"
LOG = HERE.parent / "data" / "processed" / "GENAI_cleaning-log_20260814_v02.md"

LIKERT = [
    "freq_use", "benefit_writing", "benefit_coding",
    "concern_accuracy", "concern_integrity", "concern_skill_loss",
    "overall_stance",
]
# 9 is the survey platform's sentinel for "not applicable", not a rating.
SENTINEL = 9

actions = []


def note(step, detail):
    actions.append((step, detail))
    print(f"  [{step}] {detail}")


def main():
    df = pd.read_csv(RAW, dtype=str)
    note("load", f"{len(df)} rows, {len(df.columns)} columns read from {RAW.name}")

    # 1. Whitespace. Stray spaces make " Business" a separate category from "Business".
    obj = df.select_dtypes(include="object").columns
    stripped = (df[obj] != df[obj].apply(lambda s: s.str.strip())).sum().sum()
    df[obj] = df[obj].apply(lambda s: s.str.strip())
    note("whitespace", f"trimmed leading/trailing spaces in {stripped} cell(s)")

    # 2. Case. The survey allowed free choice of role on one platform version.
    before = sorted(df["role"].unique())
    df["role"] = df["role"].str.replace(
        r"^postgraduate \(research\)$", "Postgraduate (research)", regex=True
    )
    if sorted(df["role"].unique()) != before:
        note("recode", "normalised role capitalisation: 'postgraduate (research)' -> 'Postgraduate (research)'")

    # 3. Duplicate submissions. Same respondent_id and identical payload = one person
    #    who pressed submit twice; keep the first.
    dup = df.duplicated(keep="first")
    if dup.any():
        ids = ", ".join(df.loc[dup, "respondent_id"])
        df = df[~dup].copy()
        note("duplicates", f"dropped {int(dup.sum())} exact duplicate row(s): {ids}")

    # 4. Out-of-range sentinels -> missing, so they cannot be averaged as a 9.
    for col in LIKERT:
        num = pd.to_numeric(df[col], errors="coerce")
        bad = num == SENTINEL
        if bad.any():
            ids = ", ".join(df.loc[bad, "respondent_id"])
            num = num.mask(bad)
            note("sentinel", f"{col}: recoded {int(bad.sum())} value(s) of {SENTINEL} to missing ({ids})")
        df[col] = num

    # 5. Report missingness. Nothing is imputed: n is reported per analysis instead,
    #    because with 60 respondents an imputed value would carry real weight.
    miss = df[LIKERT].isna().sum()
    for col, n in miss[miss > 0].items():
        ids = ", ".join(df.loc[df[col].isna(), "respondent_id"])
        note("missing", f"{col}: {int(n)} missing, left as missing, not imputed ({ids})")

    # 6. Derived variables used by the analysis scripts.
    df["benefit_mean"] = df[["benefit_writing", "benefit_coding"]].mean(axis=1)
    df["concern_mean"] = df[
        ["concern_accuracy", "concern_integrity", "concern_skill_loss"]
    ].mean(axis=1)
    df["cohort"] = df["role"].apply(
        lambda r: "Staff" if r == "Academic staff" else "Student"
    )
    df["n_tools"] = df["tools_used"].str.count(";") + 1
    note("derive", "added benefit_mean, concern_mean, cohort, n_tools")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT, index=False)
    note("write", f"{len(df)} rows written to {OUT.name}")

    lines = [
        "# Cleaning log -- GENAI survey",
        "",
        f"Generated by `01_clean_survey.py` from `{RAW.name}`.",
        "This file is regenerated on every run; do not edit it by hand.",
        "",
        "| Step | Action |",
        "|---|---|",
    ]
    lines += [f"| {s} | {d} |" for s, d in actions]
    lines += [
        "",
        "## Decisions that a reader may reasonably disagree with",
        "",
        "- Sentinel value 9 is treated as *not applicable*, not as a rating of 9 on a",
        "  1-5 scale. If the survey platform ever used 9 as a genuine response this",
        "  recode would be wrong, so the platform codebook should be checked at the",
        "  point the raw export is received.",
        "- Missing values are left missing rather than imputed, so n varies slightly",
        "  between analyses. Every statistic in the report states its own n.",
        "- The duplicate rule requires the whole row to match. A respondent who",
        "  submitted twice with a changed answer is *not* caught here and would need",
        "  manual review against the platform timestamps.",
    ]
    LOG.write_text("\n".join(lines) + "\n", encoding="utf-8")
    note("write", f"cleaning log written to {LOG.name}")


if __name__ == "__main__":
    print("Cleaning survey export...")
    main()
    print("Done.")
